<h1>Contact</h1>

<p class="content_1">
Do not hesitate to contact us for any problem, if you have questions, remarks, suggestions... we will answer as soon as possible.<br>
<br>
We need your feedbacks and your ideas to improve this software !<br>
Your comments is for us the best way to provide a software that fulfills the requirements of all, and for you to have a software that fulfills all your expectations !!
</p>

<h3>By mail</h3>
<p class="content_3">
To the address <a href="mailto:support.dataorganizer@gmail.com">support.dataorganizer@gmail.com</a><br>
</p>

<h3>By using our forum</h3>
<p class="content_3">
Access to our forum by <?php pagelink('forum', $lang); ?>clicking here</a>. 
There, you can read other users messages, their answers, and send your messages/answers.
</p>