<h1>Contact</h1>

<p class="content_1">
N'hésitez surtout pas à nous contacter si vous avez des problèmes, des questions, des remarques, des suggestions... nous vous répondrons dans les meilleurs délais.<br>
<br>
Nous avons besoin de vos retours et de vos idées pour améliorer ce logiciel !<br>
Avoir vos avis et commentaires est pour nous la meilleure façon de fournir un logiciel répondant aux besoins de tous, et pour vous d'avoir le logiciel correspondant exactement à vos attentes !!
</p>

<h3>Par mail</h3>
<p class="content_3">
A l'adresse <a href="mailto:support.dataorganizer@gmail.com">support.dataorganizer@gmail.com</a><br>
<!--
<br>
ou en utilisant directement le formulaire ci-dessous:
<form action="mail.php" method="post">
<?php echo "<input type='hidden' name='lang' value='".$lang."'>"; ?>
<table width=100% border=0>
<tr><td>Votre adresse:</td><td><input type="text" size="50" name="from">(pour recevoir notre réponse)</td></tr>
<tr><td>Sujet:</td><td><input type="test" size="80" name="subject"></td></tr>
<tr><td>Message:</td><td><textarea cols="80" rows="10" name="message"></textarea></td></tr>
<tr><td colspan=2><center><input type="submit" value="Envoyer"></center></td></tr>
</table>
</form>
-->
</p>

<h3>En utilisant notre forum</h3>
<p class="content_3">
Accédez à notre forum en <?php pagelink('forum', $lang); ?>cliquant ici</a>. Vous pourrez y lire les messages des autres utilisateurs, leurs réponses, et envoyer vos messages/réponses.
</p>