<h1>Download</h1>
<p class="content_1">
Download the latest version by clicking on the link below:<br>
<table class="download">
<tr><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe">
<img src="images/download_big.jpg" border=0>
</a>
</td><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe" class="download">
Free download<br>
Version <?php include('version.inc') ?>
</a>
</td></tr></table>
</p>
<br>
<p class="content_1">
The installation does not copy any file in the Windows system folders and does not use the Windows registry.<br>
It means you can install it safely, no risk to impact your system or any other installed application.<br>
<br>
The installation files takes about 73MB. The reason for this size is that a copy of Java 1.5 and a copy of VLC 
are included in the installation.<br>
This to ease the installation and ensure your system cannot be impacted: first you don't have to install them
manually; it avoids any conflict between versions; and those applications, when installed manually, copy
files in the Windows system folders, what is not done with the version we provide.
</p>
