<h1>Télechargement</h1>
<p class="content_1">
Télechargez la dernière version en cliquant sur le lien ci-dessous:<br>
<table class="download">
<tr><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe">
<img src="images/download_big.jpg" border=0>
</a>
</td><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe" class="download">
Télechargement gratuit<br>
Version <?php include('version.inc') ?>
</a>
</td></tr></table>
</p>
<br>
<p class="content_1">
L'installation ne copie aucun fichier dans les répertoires systèmes de Windows et n'utilise pas la base de registres.<br>
Vous pouvez donc l'installer en toute sécurité, sans aucun risque d'altérer votre système.<br>
<br>
Le fichier d'installation fait environ 73M. La raison de cette taille assez importante est que l'installation
contient une copie de Java 1.5, ainsi qu'une copie de VLC.<br>
En effet, afin de faciliter au maximum l'installation, et s'assurer que votre système ne peut être altéré, 
nous avons préféré embarquer ces applications. Cela vous évite tout d'abord de devoir les installer manuellement, 
ensuite cela évite des conflits entre les versions, et enfin, ces applications copient des fichiers dans vos
répertoires systèmes lorsqu'elles sont installées, ce qui n'est pas le cas avec les versions que nous avons
inclus.
</p>
