  <title>DataOrganizer - Logiciel gratuit pour organiser vos videos/films/divx, votre musique/mp3 et toutes vos données</title>
  <meta name="keywords" content="dataorganizer,logiciel,gratuit,organiser,trier,bibliotheque,video,film,musique,audio,album,donnee,telecharger,media,multimedia,open source,lecteur,mp3,avi,divx,dvd,cd,gestion,catalogue">
  <meta name="Description" content="DataOrganizer est un logiciel gratuit pour organiser vos donnees multimedia (videos/films/divx, musique/mp3) dans des bibliotheques,il recupere des informations depuis internet,integre un lecteur..">
