<table border=0 width=100%>
<tr><td>
<h1 class="content">DataOrganizer <?php include('version.inc') ?> disponible !</h1>
</td>
<td width="250">
<table class="download">
<tr><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe">
<img src="images/download_big.jpg" border=0>
</a>
</td><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe" class="download">
Télechargement gratuit<br>
Version <?php include('version.inc') ?>
</a>
</td></tr></table>
</td></tr>
<tr><td colspan=2>
<p class="content_1">
DataOrganizer est un logiciel <b>totallement gratuit</b> vous permettant 
d'<b>organiser vos vidéos/films/divx et musiques/mp3</b> de la meilleure manière qu'il soit.
<br><br>
Disponible en français et en anglais.
<br><br>
Principales fonctionnalités:
<ul>
 <li>Trier, étiquetter, commenter, noter, donner les caractéristiques de vos données</li>
 <li>Récupérer les informations de vos données automatiquement depuis Internet
  <ul>
   <li>Films: acteurs/réalisateurs/producteurs/scénaristes, résumé, critiques de la presse, critiques du public, affiche/couverture de DVD et autres détails</li>
   <li>Musique: couverture de l'album</li>
   <li>Personne (acteur...): biographie, photos, avis des utilisateurs</li>
  </ul>
 </li>
 <li>Jouer vos données directement dans le MediaPlayer intégré, ou avec n'importe quelle application installée sur votre ordinateur, ou encore visualisez les directement sur votre TV (si la Box de votre fournisseur le supporte)</li>
 <li>Recherche avancée: par type, nom, date, artiste/acteur, durée, fichier...</li>  
 <li>Créer des listes</li>
</ul>
Et encore d'autres fonctionnalités font de DataOrganizer le parfait outil pour organiser vos films et votre musique.
</p>
<p class="content_1">
Pas encore sûr ? consultez la page des <?php pagelink('features',$lang); ?>fonctionnalités détaillées et des écrans</a>.<br>
<br>
Vous voulez l'essayer ? <?php pagelink('download',$lang); ?>télechargez le</a>, c'est totallement gratuit et sans publicité. L'installation ne copie aucun fichier dans vos répertoire système ni n'utilise la base de registres, ainsi il n'impacte absolument pas votre système et vous pouvez donc l'installer en toute sécurité, et le désinstaller s'il ne vous plaît pas!<br>
<br> 
Des questions, des remarques, des idées pour améliorer ce logiciel ? <?php pagelink('contact',$lang); ?>Contactez-nous</a>!
</p>
</td>
</tr></table>
