  <title>DataOrganizer - Free software to organize and manage your videos/movies/divx, music/mp3 and all your data</title>
  <meta name="keywords" content="dataorganizer,software,free,organize,manage,sort,arrange,library,video,movie,music,audio,album,data,download,media,multimedia,open source,player,mp3,avi,divx,dvd,cd,management,catalog">
  <meta name="Description" content="DataOrganizer is a free software to organize and manage your multimedia data (videos/movies/divx, music/mp3) into libraries, it retrieves information from Internet, integrates a Media Player...">
