<table border=0 width=100%>
<tr><td>
<h1 class="content">DataOrganizer <?php include('version.inc') ?> available !</h1>
</td>
<td width="250">
<table class="download">
<tr><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe">
<img src="images/download_big.jpg" border=0>
</a>
</td><td>
<a href="http://cloud.github.com/downloads/lecousin/net.lecousin.dataorganizer/DataOrganizer-Install.exe" class="download">
Free download<br>
Version <?php include('version.inc') ?>
</a>
</td></tr></table>
</td></tr>
<tr><td colspan=2>
<p class="content_1">
DataOrganizer is a <b>completely free</b> software to 
<b>organize/manage your videos/movies/divx and music/mp3</b> in the best way.
<br><br>
Available in english and french.
<br><br>
Main features:
<ul>
 <li>Sort, label, comment, note, give the characteristics of your data</li>
 <li>Retrieve information about your data automatically from Internet
  <ul>
   <li>Movies: actors/directors/producers/writers, synopsis, press reviews, public reviews, poster/DVD cover and other details</li>
   <li>Music: album covers</li>
   <li>People (actor...): biography, photos, users comments</li>
  </ul>
 </li>
 <li>Play your data directly in the integrated MediaPlayer, or with any application installed on your computer, or play them directly on your TV (if the Box of your provider supports it)</li>
 <li>Advanced search: by type, name, date, artist/actor, duration, file...</li>  
 <li>Create lists</li>
</ul>
And a lot of other features that make DataOrganizer the perfect tool to organize and manage your movies and music albums.
</p>
<p class="content_1">
Not yet sure ? have a look at the <?php pagelink('features',$lang); ?>detailled features and screenshots</a>.<br>
<br>
Want to try it ? <?php pagelink('download',$lang); ?>download it</a>, it's completely free, no ads. The installation does not copy any file in your system folders and does not use the Windows registry, so it does not impact your system and you can install it safely; and uninstall it if you don't like it!<br>
<br> 
Any question, remark, idea to improve this software ? <?php pagelink('contact',$lang); ?>Contact us</a>!
</p>
</td>
</tr></table>
