<?php

$db_settings = array();
$db_settings['host'] = 'localhost';
$db_settings['user'] = 'dataorganizer_do';
$db_settings['pass'] = '5altefj7';
$db_settings['db'] = 'dataorganizer_db';
$db_settings['forum_admin_table'] = 'forum_admin';
$db_settings['forum_categories_table'] = 'forum_categories';
$db_settings['forum_category_names_table'] = 'forum_category_names';
$db_settings['forum_posts_table'] = 'forum_posts';

?>
